### ISSUE TITLE
导入AndroidStudio无法使用

### ISSUE THREAD

**Issue by zhiyu-zeng** [Mosect/apk2gradle#1]
导入androidStudio后res/drawable目录下有带$字段命名的xml文件，无法通过编译，需要把名称更改，在把所有引用的更改才能通过编译
![image](https://user-images.githubusercontent.com/54022707/147636150-437f5d03-a7ef-43c8-b1a2-6966cbdcdec7.png)

**Comment by Mosect** [comment]
你好，请问这个是什么类型apk？是系统级的apk吗？还是经过混淆后的apk？如果可以的，提供一下apk或者R类文件内容

**Comment by zhiyu-zeng** [comment]
不是系统，就是普通应用层app，直接用AS打开 Empty Activity 生成的APK，to gradle后导入 AS 
 
![image](https://user-images.githubusercontent.com/54022707/147801264-409f9797-b515-4aa4-b5e7-07ac114cc9dc.png)

**Comment by zhiyu-zeng** [comment]
https://wwi.lanzouq.com/iGFvcy6614b

**Comment by Mosect** [comment]
已更新版本1.1.0，修复了诸多问题

**Comment by Mosect** [comment]
直接运行，暂时只支持release版本，不支持debug
